sudo: required 
services:
  - docker 
  
before_install:
  - docker build -t gcetin/react-docker-travisci-elasticbeanstalk -f Dockerfile.dev .


#-- --coverage is to launch to prompt after execute npm run test command. since when only npm run test is run, it's not exiting to prompt and 
# is requesting other input in prompt interface from keyboard like p,t etc. so 
script: 
  - docker run gcetin/react-docker-travisci-elasticbeanstalk npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-468109815766"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"